naam = input("Wat is uw naam? ")
adres = input("Wat is uw adres? ")
postcode = input("Wat is uw postcode? ")
woonplaats = input("Wat is uw woonplaats? ")

print(" -----------------------------------------")
print("-----------")
print("|   Naam         :  ", naam)
print("|   Adres        :  ", adres)
print("|   Postcode     :  ", postcode)
print("|   Woonplaats   :  ", woonplaats)
print(" -----------------------------------------")
print("-----------")